### ISSUE TITLE
How to expose and use port(s)

### ISSUE THREAD

**Issue by kujiy** [colinmollenhour/haproxy-service#4]
Hi @colinmollenhour ,
I started to try using your galera image. I was succeeded to build [galera stack along with your swarm instruction](https://github.com/colinmollenhour/mariadb-galera-swarm/tree/master/examples/swarm) on bare metals. Now thinking about the routing because Docker ingress network must get round robin. Some instructions suggest it's better to write into only one node. I think this haproxy image could be that when use with [your haproxy cfg in here](https://github.com/colinmollenhour/mariadb-galera-swarm/issues/5#issuecomment-328923763). But I couldn't get it clearly, so I have a favor to ask you.
That haproxy tpl seems to bind 3306 for write and 3307 for read. I'm wondering how my mysql clients can split the request to both ports. Do you use maxscale before this haproxy? Are you using this haproxy with `docker network connect` to the galera cluster's network?

I'm sorry I'm still too beginner but I'll be able to help growing these images in the future!

**Comment by colinmollenhour** [comment]
My HAProxy example assumes that your application can already split read/write connections. If it doesn't support splitting on it's own and it is hard to implement then you're probably better off using a more robust proxy like MySQL Proxy or MaxScale.
